options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    id: 'Build with Maven'
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'functions', 'deploy', 'storage-function',
      '--gen2',
      '--runtime=java17',
      '--entry-point=gcfv2storage.StorageFunction',
      '--source=.',
      '--trigger-http',
      '--region=asia-northeast1'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth print-access-token > access.token
        echo "<settings>...</settings>" > settings.xml # settings.xml に埋め込む
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['-s', 'settings.xml', 'clean', 'package', '-DskipTests']
    ]
